---

- name: Network Getting Started First Playbook
  connection: network_cli
  gather_facts: false
  hosts: all
  tasks:
      - name: return motd to registered var
        command: cat /etc/motd
        register: mymotd